version: 2.1

executors:
  cypress-executor:
    docker:
      - image: cypress/browsers:node-18.16.0-chrome-120
    working_directory: ~/repo

jobs:
  run-cypress-tests:
    executor: cypress-executor
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm ci

      - run:
          name: Run Cypress tests
          command: npx cypress run

      - store_artifacts:
          path: cypress/videos
          destination: cypress-videos

      - store_artifacts:
          path: cypress/screenshots
          destination: cypress-screenshots

      - store_test_results:
          path: cypress/results

workflows:
  cypress-tests-workflow:
    jobs:
      - run-cypress-tests
